sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t seba2312/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true seba2312/docker-react npm run test
